name: tQuests
author: tanko
version: '${project.version}'
main: tanko.tquests.TQuests
api-version: 1.18
softdepend: [Citizens, tInteractions,Vault,MythicMobs]
commands:
  quest:
    description: quest command
    usage: /<command>
    permission: tquests.commands.admin.quest
  step:
    description: step command
    usage: /<command>
    permission: tquests.commands.admin.step
  reward:
    description: reward command
    usage: /<command>
    permission: tquests.commands.admin.reward
  condition:
    description: condition command
    usage: /<command>
    permission: tquests.commands.admin.condition